### PR TITLE
style: fix pixel affine table

### LINKED ISSUE #340: Affine Transformation Table Cutoff on Windows
* pymmcore-widgets version: 0.7.2
* Python version: 3.12.4
* Operating System: Windows 11

### Description

It seems that the Affine Transformation Table is cutoff on Windows. Is this a styling thing that we could fix? It's a bit frustrating in that scrolling the table *requires* the scrollbar, as the scroll behavior for the cells changes the value of that particular cell.

Also of note (via @marktsuchida) is that the "s" on "Affine Transformations" should probably go (it's only one transformation?)

image

### PR DESCRIPTION
**Pull request by tlambert03**
closes #340

### CODE REVIEW

**Comment by gselzer** [comment]
Wow, speedy again @tlambert03!

I checked out 8a49893, and I unfortunately still see the issue 😕. I actually tried something similar yesterday, and was not successful. I can continue tinkering later if you'd like...

image

**Comment by tlambert03** [comment]
ok, then the minimumSizeHint is not working on your display for some reason.  on my windows it looks fine, but I don't have windows 11.  can you show a screenshot of your display settings?  including the scale and layout?

**Comment by tlambert03** [comment]
can you edit the source code to this, and let me know how it looks?

```
    self.verticalHeader().setDefaultSectionSize(20)

    def sizeHint(self):
        sz = self.minimumSizeHint()
        sz.setHeight(self.rowHeight(0) * 3 + 2)
        return z
```

**Comment by gselzer** [comment]
diff:
```diff
diff --git a/src/pymmcore_widgets/_pixel_configuration_widget.py b/src/pymmcore_widgets/_pixel_configuration_widget.py
index ebfebd4..85b4a83 100644
--- a/src/pymmcore_widgets/_pixel_configuration_widget.py
+++ b/src/pymmcore_widgets/_pixel_configuration_widget.py
@@ -482,9 +482,12 @@ class AffineTable(QTableWidget):
         # add a spinbox in each cell of the table
         self._add_table_spinboxes()
         self.setValue(DEFAULT_AFFINE)
+        self.verticalHeader().setDefaultSectionSize(20)
 
     def sizeHint(self) -> Any:
-        return self.minimumSizeHint()
+        sz = self.minimumSizeHint()
+        sz.setHeight(self.rowHeight(0) * 3 + 2)
+        return sz
 
     def _add_table_spinboxes(self) -> None:
         """Add a spinbox in each cell of the table."""
```

result of `python pymmcore-widgets/examples/pixel_configuration_widget.py`:
image

**Pull request merged**
