### PR TITLE
test: add napari-micromanager test

### LINKED ISSUE #158: test: add test of upstream napari-micromanager
Since napari-micromanager is dependent on everything here I'm finding that changes here are breaking things there. For example this line:

https://github.com/pymmcore-plus/pymmcore-widgets/blob/58f35f4c3fdcdf8e830c301d4a3de8215c1a948b/src/pymmcore_widgets/_mda/_mda_widget.py#L219

which was recently added in #140 results in this error for napari-micromanager:

```
AttributeError                            Traceback (most recent call last)
File ~/Documents/oss/micro/napari-micromanager/src/napari_micromanager/_gui_objects/_toolbar.py:369, in MicroManagerToolbar._show_dock_widget(self=<napari_micromanager.main_window.MainWindow(0x55f386059e80)>, key='MDA')
    363 except KeyError as e:
    364     raise KeyError(
    365         "Not a recognized dock widget key. "
    366         f"Must be one of {list(DOCK_WIDGETS)} "
    367         " or the `whatsThis` property of a `sender` `QPushButton`."
    368     ) from e
--> 369 wdg = wdg_cls(parent=self, mmcore=self._mmc)
        self = <napari_micromanager.main_window.MainWindow(0x55f386059e80) at 0x7f538811a7c0>
        wdg_cls = <class 'napari_micromanager._gui_objects._mda_widget.MultiDWidget'>
        self._mmc = <CMMCorePlus at 0x7f538092eb10>
    371 if isinstance(wdg, PropertyBrowser):
    372     wdg.setSizePolicy(
    373         QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding
    374     )

File ~/Documents/oss/micro/napari-micromanager/src/napari_micromanager/_gui_objects/_mda_widget.py:23, in MultiDWidget.__init__(self=<napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110)>, parent=<napari_micromanager.main_window.MainWindow(0x55f386059e80)>, mmcore=<CMMCorePlus>)
     20 def __init__(
     21     self, *, parent: QWidget | None = None, mmcore: CMMCorePlus | None = None
     22 ) -> None:
---> 23     super().__init__(include_run_button=True, parent=parent, mmcore=mmcore)
        parent = <napari_micromanager.main_window.MainWindow(0x55f386059e80) at 0x7f538811a7c0>
        mmcore = <CMMCorePlus at 0x7f538092eb10>
     25     self._save_groupbox = SaveWidget()
     26     self._save_groupbox.setSizePolicy(
     27         QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed
     28     )

File ~/Documents/oss/micro/pymmcore-widgets/src/pymmcore_widgets/_mda/_mda_widget.py:211, in MDAWidget.__init__(self=<napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110)>, parent=<napari_micromanager.main_window.MainWindow(0x55f386059e80)>, include_run_button=True, mmcore=<CMMCorePlus>)
    208     self.buttons_wdg.run_button.clicked.connect(self._on_run_clicked)
    209     self.buttons_wdg.run_button.show()
--> 211 self._on_sys_cfg_loaded()
        self = <napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110) at 0x7f5380b029c0>
    213 self.destroyed.connect(self._disconnect)

File ~/Documents/oss/micro/pymmcore-widgets/src/pymmcore_widgets/_mda/_mda_widget.py:219, in MDAWidget._on_sys_cfg_loaded(self=<napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110)>)
    217     self._mmc.setChannelGroup(channel_group)
    218 self._enable_run_btn()
--> 219 self._update_total_time()
        self = <napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110) at 0x7f5380b029c0>

File ~/Documents/oss/micro/pymmcore-widgets/src/pymmcore_widgets/_mda/_mda_widget.py:494, in MDAWidget._update_total_time(self=<napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110)>)
    491 t_per_tp_msg = ""
    492 _uses_time = self._uses_time()
--> 494 for e in self.get_state():
        self = <napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110) at 0x7f5380b029c0>
    495     if e.exposure is None:
    496         continue

File ~/Documents/oss/micro/napari-micromanager/src/napari_micromanager/_gui_objects/_mda_widget.py:67, in MultiDWidget.get_state(self=<napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110)>)
     63 def get_state(self) -> MDASequence:
     64     sequence = cast(MDASequence, super().get_state())
     65     sequence.metadata[SEQUENCE_META_KEY] = SequenceMeta(
     66         mode="mda",
---> 67         split_channels=self.checkBox_split_channels.isChecked(),
        sequence = MDASequence(
   channels=(Channel(config='DAPI', group='Channel', exposure=10.0, do_stack=True, z_offset=0.0, acquire_every=1, camera=None),),
   stage_positions=(Position(x=-0.0, y=-0.0, z=0.0, name='Pos000', sequence=None),),
)
        sequence.metadata = {}
        SEQUENCE_META_KEY = 'napari_mm_sequence_meta'
        self = <napari_micromanager._gui_objects._mda_widget.MultiDWidget(0x55f387b3b110) at 0x7f5380b029c0>
     68         **self._save_groupbox.get_state(),
     69     )
     70     return sequence

AttributeError: 'MultiDWidget' object has no attribute 'checkBox_split_channels'
```

We could catch these errors earlier by running the napari-micromanager test suite as part of the CI on this repo. In addition it would also be a nice form of integration testing for everything here.

### PR DESCRIPTION
**Pull request by tlambert03**
adds a test for napari-micromanager, for heads up if we break it

Closes #158

### CODE REVIEW

**Review by ianhi — APPROVED** [review]
Nice! Seems to in fact be catching errors.

**Comment by ianhi** [comment]
re-running the failed test to check that it fails with a new error given the recent changes in napari-micro

**Comment by ianhi** [comment]
ok to merge @tlambert03 or did you want to wait until all these are passing?

**Comment by tlambert03** [comment]
i'd prefer to have it fixed before we merge.  I don't want to be stuck with a red x and everything failing due to an external library.  I know it requires two-repo collaboration but that was the goal of this PR

**Pull request merged**
