### PR TITLE
feat: Points plan selector

### PR DESCRIPTION
**Pull request by tlambert03**
this pulls out the left half of the FOV selector into a useq widget whose value is one of a number of relative point plans.  Next step is to put it back into a joint widget with the view on the right side, connect it's valueChanged to update the view

(this is modified from @fdrgsp's code in #308 and he is marked as author in the git history)

### CODE REVIEW

**Comment by fdrgsp** [comment]
@tlambert03 can we make the `single FOV` text `bold` and `centered` as random points and grid? and Is it ok to have all of them in a `QGroupBox`?

**Comment by tlambert03** [comment]
yep!

**Comment by tlambert03** [comment]
just  a moment

**Review by fdrgsp — APPROVED** [review]
❤️

**Comment by tlambert03** [comment]
all set

**Comment by fdrgsp** [comment]
@tlambert03 ready to merge?

**Comment by tlambert03** [comment]
yep!

**Pull request merged**
