### PR TITLE
[WIP] feat: add combo for micromanager Focus and Autofocus to PositionTable

### PR DESCRIPTION
**Pull request by fdrgsp**
merge after #140.

note: tests will fail until useq-schema is upgraded (I'm working on a PR for that)

This PR adds "control" for micromanager `Focus` and `AutoFocus` (e.g. Nikon PFS) devices.

This PR is linked to https://github.com/pymmcore-plus/useq-schema/issues/4 and https://github.com/pymmcore-plus/pymmcore-plus/issues/51#issuecomment-1397585287.

Screenshot 2023-05-23 at 3 57 54 PM

to test:
```python
from pymmcore_plus import CMMCorePlus
from pymmcore_widgets._mda import PositionTable
mmc = CMMCorePlus.instance()
cfg = "./tests/test_config.cfg"
mmc.loadSystemConfiguration(cfg)
p = PositionTable()
p.show()
```

### CODE REVIEW

**Comment by ianhi** [comment]
I will try this on a real scope tomorrow!

**Comment by ianhi** [comment]
This looks really nice! But is it possible to pull out just those changes rather than combining with the grid changes?

**Comment by fdrgsp** [comment]
> This looks really nice! But is it possible to pull out just those changes rather than combining with the grid changes?

@ianhi you can try with this I think https://github.com/fdrgsp/pymmcore-widgets/tree/z_autofocus_ian ...let me know if there is something broken...

**Comment by ianhi** [comment]
> @ianhi you can try with this I think https://github.com/fdrgsp/pymmcore-widgets/tree/z_autofocus_ian ...let me know if there is something broken...

Can you either (1) make this PR only that commit or (2) make a new PR based on that branch?

**Comment by fdrgsp** [comment]
note: tests will fail until we add `z_focus` and `z_autofocus` to `useq` `Position` object.

**Comment by fdrgsp** [comment]
continue in #147

**Pull request closed without merging**
